
name: Build and Release

env:
  RELEASE_VERSION: "v1.1.0"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Build and Package

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ThirdPerson-Revamped.sln

      - name: Build
        run: dotnet build ThirdPerson-Revamped.sln --configuration Release

      - name: List build output
        run: |
          echo "ThirdPerson output:"
          dir .\ThirdPerson\bin\Release\net8.0\
          echo "CS2TraceRay output:"
          dir .\CS2TraceRay\bin\Release\net8.0\

      - name: Create folders for packaging
        run: |
          mkdir -p package/addons/counterstrikesharp/plugins/ThirdPersonRevamped
          mkdir -p package/addons/counterstrikesharp/shared/CS2TraceRay
          mkdir -p package/addons/counterstrikesharp/gamedata

      - name: Copy plugin DLLs and gamedata
        run: |
          copy .\ThirdPerson\bin\Release\net8.0\ThirdPersonRevamped.dll package\addons\counterstrikesharp\plugins\ThirdPersonRevamped\
          copy .\ThirdPerson\bin\Release\net8.0\CS2TraceRay.dll package\addons\counterstrikesharp\shared\CS2TraceRay\
          copy .\CS2TraceRay\CS2TraceRay.gamedata.json package\addons\counterstrikesharp\gamedata\

      - name: Zip package (versioned)
        run: |
          Compress-Archive -Path package/addons/* -DestinationPath "ThirdPersonRevamped-${{ env.RELEASE_VERSION }}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ThirdPersonRevamped-${{ env.RELEASE_VERSION }}
          path: ThirdPersonRevamped-${{ env.RELEASE_VERSION }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ThirdPersonRevamped-${{ env.RELEASE_VERSION }}.zip
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ThirdPersonRevamped ${{ env.RELEASE_VERSION }}
          generate_release_notes: true
